name: Update README Documentation

on:
  push:
    branches: [main]
    paths:
      - "scripts/**"
      - "examples/**"
      - "action.yml"
  pull_request:
    branches: [main]
    paths:
      - "scripts/**"
      - "examples/**"
      - "action.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --break-system-packages

      - name: Generate documentation examples
        run: |
          python scripts/generate_readme_docs.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes (main branch)
        if: github.ref == 'refs/heads/main' && steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "docs: Auto-update README with latest examples and task definition"
          git push

      - name: Comment on PR (pull request)
        if: github.event_name == 'pull_request' && steps.check_changes.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const readmeContent = fs.readFileSync('README.md', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📋 README Documentation Updated

            This PR includes changes that would update the README documentation. The updated examples and task definition would be automatically applied when merged to main.

            <details>
            <summary>Preview of updated README sections</summary>

            The README will be automatically updated with:
            - Latest full YAML configuration example
            - Corresponding generated task definition JSON
            - All currently available features and options

            </details>`
            });
